# Generated by Django 2.0.7 on 2018-09-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20180530_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('view_toners', 'Can View Toners'), ('view_general', 'Can View All Tabs'))},
        ),
    ]
