# Generated by Django 2.0.7 on 2018-09-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_auto_20180920_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('view_toners', 'Can View Toners'), ('edit_toners', 'Can Edit Toners'), ('view_general', 'Can View All Tabs'))},
        ),
    ]
