# Generated by Django 2.0.7 on 2018-10-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_auto_20180924_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'permissions': (('view_brands', 'Can View Brands'),)},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('view_companies', 'Can View Companies'),)},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('view_departments', 'Can View Departments'),)},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': (('view_devices', 'Can View Devices'),)},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'permissions': (('view_requests', 'Can View Requests'),)},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'permissions': (('view_statuses', 'Can View Statuses'),)},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={'permissions': (('view_technicians', 'Can View Technicians'),)},
        ),
    ]
