# Generated by Django 2.0.7 on 2018-10-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20181024_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'permissions': (('view_buildings', 'Can View Building'),),
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, null=True)),
                ('floor', models.CharField(max_length=100, null=True)),
                ('room', models.CharField(max_length=100, null=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('notes', models.TextField(null=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.Brand')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.Building')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests.Department')),
            ],
            options={
                'permissions': (('view_printers', 'Can View Printers'),),
            },
        ),
    ]
