# Generated by Django 2.0.7 on 2018-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_building_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='barcode',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='reference',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
