# Generated by Django 2.0.7 on 2018-10-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_auto_20181030_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
